# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            BME UNITE
tagline:          'Underrepresented Needs In Technology & Engineering'
description:      'Underrepresented Needs In Technology & Engineering'
url:              https://bmeunite.org
baseurl:          https://bmeunite.org/

paginate:         5

github:
  repo:           https://github.com/BME-UNITE/bmeunite

plugins:
  - details_tag